title: HackademINT
description: Club de cybersécurité de Telecom SudParis
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
lang: 'fr-FR'
github:
  repository_url: 'https://github.com/HackademINT/hackademint.github.io'
author:
  name: "HackademINT"
  email: "hackademint@listes.minet.net"
  url: "https://hackademint.org"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 100
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-menus

owner : "HackademINT"
year : "2020"
